#+Title: Main setup files
#+Author: Systems Team
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document contains the initial scripts that are used to run all
  the playbooks in a sequential order
* Implementation
** Base Machine Setup
   The following script configures base machine with OpenVZ
   virtualization.
   
   The playbook runs on localhost( host machine). It takes two roles
   that are 1. [[./base-setup.org][basesetup]] 2. [[./base-setup.org][openvz]]
#+BEGIN_SRC yml :tangle base-machine-setup.yml
---
- hosts: localhost
  roles:
     - basesetup
     - openvz

#+END_SRC

** Network Configuration
   Following roles configures network in each container. And Copies
   host machine's public key to config-server.
#+begin_src yml :tangle servers-network-configuration.yml
---
- hosts: localhost
  roles:
    - cluster
    - router
    - ansible
    - public-dns-server
    - private-dns-server
    - ossec-server
    - rsyslog-server
    - reverse-proxy-server
    - rsnapshot-server
    - nagios-server
    - ads-server
    - copy-ssh-keys-to-config-server

#+end_src

** Configuration Server
   Following script uses config-server role and configures
   config-server with basic requirements. For more about what
   config-server roles does, click [[./ansible-server.org][here]]
#+begin_src yml :tangle config-server.yml
---
- hosts: config-server
  become_user: root

  roles:
    - config-server


#+end_src

** Configure cluster containers with vlead user
   Once the cluster is created and configured network, then the
   following script configures services rsyslog,dns servers,
   reverseproxy, nagios, ads and rsnapshot using vlead user on
   config-server. For more details about config-with-vlead-user roles
   please go [[./ansible-server.org][here]]

#+begin_src yml :tangle config-with-vlead-user.yml
---
- hosts: config-server
  become: yes
  become_user: vlead
  roles:
   - config-with-vlead-user

#+end_src
** Cluster Configuration file
   All above playbooks are includes in the following ansible script.
   Once the =base-machine-setup.yml= is done, system will be
   restarted. After restart, following script does remaining cluster
   automation.
#+begin_src yml :tangle cluster.yml

---
- include: servers-network-configuration.yml
- include: config-server.yml
- include: config-with-vlead-user.yml

#+end_src
